---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: lht-awx-nonprod
  namespace: awx-nonprod
spec:
  service_type: ClusterIP
  ingress_type: Route
  route_host: awx-test.apps.svc.az.lhtcloud.com
  route_tls_termination_mechanism: Edge
  #postgres_image: registry.redhat.io/rhel9/postgresql-13:latest
  # postgres_configuration_secret: lht-awx-external-postgres-configuration
  redis_image: redis
  redis_image_version: "7"
  # image_pull_secrets:
	# - default-quay-onecloud-svc
  ipv6_disabled: true
  auto_upgrade: true
  image: quay.io/ansible/awx
  image_version: 21.13.0
  control_plane_priority_class: nonprod
  task_privileged: false
  replicas: 1
  web_resource_requirements:
	requests:
	  cpu: 150m
	  memory: 300Mi
	limits:
	  cpu: 300m
	  memory: 500Mi
  task_resource_requirements:
	requests:
	  cpu: 250m
	  memory: 300Mi
	limits:
	  cpu: 500m
	  memory: 500Mi
  ee_resource_requirements:
	requests:
	  cpu: 150m
	  memory: 100Mi
	limits:
	  cpu: 200m
	  memory: 500Mi
  node_selector: |
	lufthansatechnik.de/zone: app