---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: lht-awx-nonprod
  namespace: awx-nonprod
spec:
  service_type: ClusterIP
  ingress_type: Route
  route_host: "127.0.0.1:8080"
  route_tls_termination_mechanism: Edge
  redis_image: "http://127.0.0.1:5001/redis"
  redis_image_version: "7"
  ipv6_disabled: true
  auto_upgrade: true
  image: quay.io/ansible/awx
  image_version: 21.13.0
  control_plane_priority_class: nonprod
  task_privileged: false
  replicas: 1
  web_resource_requirements:
    requests:
      cpu: 150m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 500Mi
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 300Mi
    limits:
      cpu: 500m
      memory: 500Mi
  ee_resource_requirements:
    requests:
      cpu: 150m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 500Mi
  node_selector:
    lufthansatechnik.de/zone: app
