apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/ansible/awx-operator/config/default?ref=1.3.0
- awx.yaml
- postgres-configuration.yaml

images:
# - name: gcr.io/kubebuilder/kube-rbac-proxy
#   newName: hub/kube-rbac-proxy
#   newTag: v0.13.0
- name: quay.io/ansible/awx-operator
  newTag: 1.3.0

# patches:
# - patch: |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: controller-manager
#       namespace: system
#     spec:
#       template:
#         spec:
#           imagePullSecrets:
#             - name: default-quay-onecloud-svc
#           containers:
#             - name: kube-rbac-proxy
#               resources:
#                 requests:
#                   cpu: 25m
#                   memory: 64Mi
#             - name: awx-manager
#               resources:
#                 limits:
#                   cpu: 1
#                   memory: 1024Mi
#               env:
#                 - name: ANSIBLE_DEBUG_LOGS
#                   value: 'true'
#   target:
#     kind: Deployment
#     name: controller-manager
# namespace: awx-nonprod

